version: "3.9"
services:
  ecomm:
    image: gabrielamarchiori/app-ecomm:1.0
    container_name: ecomm
    ports:
      - 3000:3000
    depends_on:
      - mongo-ecomm
    environment:
      - MONGO_HOST=${MONGO_HOST:-127.0.0.1}
  mongo-ecomm:
    image: mongo
    container_name: mongo-ecomm
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - db-mongo-ecomm:/data/db
      - type: bind
        source: ./mongo
        target: /mongo-scripts
    restart: always
    ports: 
      - 27017:27017
volumes: 
  db-mongo-ecomm: 

  
