openapi: 3.0.3
info: 
  title: API ECOMM
  description: API que controla os produtos, categorias e vendas de uma loja, bem coomo mantém um cadastro de seus compradores.
  version: 0.0.1
  termsOfService: https://mockapi.io
  contact:
    name: Suporte a Devs
    email: contato@example.com
    url: https://mockapi.io
  license:
    name: "Licença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
  description: Documentação burocrática
  url: https://mockapi.io
servers: 
  - url: http://localhost:3000
    description: API ECOMM
paths:
  /api/categories:
    get:
      tags: 
        - categories
      summary: Busca todas as categorias dos produtos existentes na loja
      responses:
        200: 
          description: Sucesso
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Categories"
  /api/admin/categories:
    post:
      tags: 
        - categories
      summary: Cria nova especialidade
      description: "Através dessa endpoint você pode criar novas especialidade"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome: 
                  type: string
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
            
          
  /api/categories/{id}:
    parameters: 
    - name: id
      in: path
      schema:
        type: string
        format: objectId
      required: true
    get:
      tags: 
        - categories
      summary: Busca especialidade pelo ID
      responses: 
        200:
          description: Sucesso
          content:
             application/json:
              schema:
                $ref: "#/components/schemas/Category"
        '404':
          description: Especialidade não encontrada
          content:
            application/json:
              example: "especialidade não encontrada"
    delete:
      tags: 
        - categories
      summary: Deleta especialidade por ID
      responses:
        '204':
          description: The resource was deleted successfully
    patch:
      tags: 
        - categories
      summary: Edita as especialidades
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome: 
                  type: string
                status:
                  type: string
      responses:
         200:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
components:
  schemas:
    Category:
      type: object
      properties:
        id: 
          type: string
          format: objectId
        nome: 
          type: string
        status:
          type: string
    Categories:
      type: array
      items:
        $ref: "#/components/schemas/Category"
  
     
      
        
          
            
      
    
    
            
                  
                
                  
  